= Glossary of Terms

== Kubernetes

https://kubernetes.io/

Kubernetes (K8s) is an open-source system for automating deployment, scaling, and management of containerized applications.

Kubernetes groups containers (Docker or CRI-O) that make up an application into logical units for easy management and discovery. Kubernetes builds upon 15 years of experience of running production workloads at Google, combined with best-of-breed ideas and practices from the community.

=== Docker

http://docker.com

Docker is a tool designed to make it easier to create, deploy, and run applications by using containers. Containers allow a developer to package up an application with all of the parts it needs, such as libraries and other dependencies, and ship it all out as one package. By doing so, thanks to the container, the developer can rest assured that the application will run on any other Linux machine regardless of any customized settings that machine might have that could differ from the machine used for writing and testing the code.

=== Crio-O

https://cri-o.io/

CRI-O is an implementation of the Kubernetes CRI (Container Runtime Interface) to enable using OCI (Open Container Initiative) compatible runtimes. It is a lightweight alternative to using Docker as the runtime for kubernetes. It allows Kubernetes to use any OCI-compliant runtime as the container runtime for running pods. Today it supports runc and Kata Containers as the container runtimes but any OCI-conformant runtime can be plugged in principle.



== OpenShift

Red Hat OpenShift is a Kubernetes platform for standardized, self-service dev environments and full-stack automated ops, designed to allow the enterpirse to focus on the code that will make a difference (instead of Kubernetes and its' related infrastructure concerns.)

== Strimzi

https://strimzi.io/

Strimzi provides a simple, efficient way to run an Apache Kafka cluster on Kubernetes (and OpenShift) with various configurations.

== Apache Kafka

==== Namespace

https://docs.openshift.com/container-platform/3.11/architecture/core_concepts/projects_and_users.html#namespaces

A Kubernetes namespace provides a mechanism to scope resources in a cluster. In OpenShift, a project is a Kubernetes namespace with additional annotations.  Namespaces provide a unique scope for:

* Named resources to avoid basic naming collisions.
* Delegated management authority to trusted users.
* The ability to limit community resource consumption.

Most objects in the system are scoped by namespace, but some are excepted and have no namespace, including nodes and users.

==== Service Accounts

https://docs.openshift.com/container-platform/3.11/dev_guide/service_accounts.html

Service accounts provide a flexible way to control API access without sharing a regular user’s credentials.

When a person uses the OpenShift Container Platform CLI or web console, their API token authenticates them to the OpenShift API. However, when a regular user’s credentials are not available, it is common for components to make API calls independently. For example:

* Replication controllers make API calls to create or delete pods.
* Applications inside containers could make API calls for discovery purposes.
* External applications could make API calls for monitoring or integration purposes.

Service Accounts allow these and similar functions to be executed by agents other than a particular user

==== Operator Framework

https://docs.openshift.com/container-platform/3.11/install_config/installing-operator-framework.html

The Operator Framework is an open source toolkit designed to manage Kubernetes native applications, called Operators, in a more effective, automated, and scalable way.  CoreOS, which became part of Red Hat in 2018, created the Operator Framework.



==== Custom Resource Definition

https://docs.openshift.com/container-platform/3.11/dev_guide/creating_crd_objects.html#crd_dev-guide-crd

In the Kubernetes API a resource is an endpoint that stores a collection of API objects of a certain kind. For example, the built-in pods resource contains a collection of Pod objects.

A custom resource is an object that extends the Kubernetes API or allows you to introduce your own API into a project or a cluster.

A custom resource definition (CRD) file defines your own object kinds and lets the API Server handle the entire lifecycle.

==== OpenShift Client Tools

https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html

The OpenShift Online CLI exposes commands for managing your applications, as well as lower level tools to interact with each component of your system. 

===== oc login 
The oc login command is the best way to initially set up the CLI, and it serves as the entry point for most users. The interactive flow helps you establish a session to an OpenShift Online server with the provided credentials. The information is automatically saved in a CLI configuration file that is then used for subsequent commands.